# Generated by Django 5.1.6 on 2026-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_url',
            field=models.CharField(blank=True, help_text='URL đầy đủ hoặc đường dẫn tương đối (vd /audio/...) cho file nghe gắn bài.', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.CharField(blank=True, help_text='File âm thanh cho câu listening (ưu tiên hơn lesson.audio_url).', max_length=500),
        ),
    ]
