# Generated by Django 5.1.6 on 2026-04-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_question_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Hình minh học (text-only có thể để trống).', max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='audio_url',
            field=models.CharField(blank=True, default='', help_text='URL hoặc đường dẫn tương đối cho audio (text-only có thể để trống).', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_url',
            field=models.CharField(blank=True, default='', help_text='Audio cho câu listening (không dùng thì để trống).', max_length=500),
        ),
    ]
