# Generated by Django 6.0.4 on 2026-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_skill_cefr_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mã khóa trong file fixture (vd: C01).', max_length=32),
        ),
    ]
