# Generated by Django 6.0.4 on 2026-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, default='', help_text='Lời thoại/script audio (listening). Hiển thị trên trang bài tập, không phải trang tài liệu.'),
        ),
    ]
