# Generated by Django 6.0.4 on 2026-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='reading_passage',
            field=models.TextField(blank=True, default='', help_text='Đoạn đọc chính (reading). Hiển thị trên trang bài tập; tab Tài-liệu chỉ preparation.'),
        ),
    ]
