# Generated by Django 5.1.6 on 2026-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_reading_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='skill_type',
            field=models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20),
        ),
    ]
